### ISSUE TITLE
Training source and labels different sizes

### ISSUE THREAD

**Issue by shanestorks** [azpoliak/robust-nli#7]
I'm having the following error when trying to re-train the model on SNLI (configured for testing on SPRL):

`Traceback (most recent call last):
  File "train.py", line 423, in <module>
    main(args)
  File "train.py", line 328, in main
    args.max_train_sents, args.max_val_sents, args.max_test_sents, args.remove_dup)
  File "/home/sstorks/robust-nli/src/data.py", line 82, in get_nli_text
    train = extract_from_file(train_lbls_file, train_src_file, max_train_sents, "train", remove_dup)
  File "/home/sstorks/robust-nli/src/data.py", line 42, in extract_from_file
    assert len(lbls) == len(srcs), "%s: %s labels and source files are not same length" % (lbls_file, data_split)
AssertionError: ../data/snli_1.0/cl_snli_train_lbl_file: train labels and source files are not same length`

I used the provided script to download the data. Any ideas why this would be happening? Thank you!

**Comment by boknilev** [comment]
No idea, maybe something changed in the data source?

**Comment by shanestorks** [comment]
It appears the [get_data.sh](data/get_data.sh) script expects the SNLI zip file to have files for the "test_hard" partition, but it doesn't. This causes an error in the [convert_snli.py](data/convert_snli.py) script and the "source" files for all other partitions to be empty.

The problem can be temporarily resolved by removing "test_hard" from line 5 in [convert_snli.py](data/convert_snli.py). This prevents us from reproducing any experiments with that dataset. Not sure where those files can be found.

**Comment by shanestorks** [comment]
There's a resource missing from the nltk installation which causes the processing of all records in the SNLI files to fail. The issue can be resolved by running `nltk.download('punkt')` in Python.
